name: Infrastructure Only Deployment

on:
  release:
    types: [ published ]

env:
  AWS_REGION: us-east-1

jobs:
  deploy-infrastructure:
    name: Deploy AWS Infrastructure Only
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ~1.0
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Deploy Infrastructure
      run: |
        cd infrastructure
        terraform init
        terraform plan -var='environment=production' -out=tfplan
        terraform apply tfplan
        
    - name: Output Infrastructure Details
      run: |
        cd infrastructure
        terraform output
